const gamesData = [
  {
    "title": "Catan",
    "synopsis": "Coloniza una isla gestionando recursos y negociando para construir ciudades.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 10,
    "playersMin": 3,
    "playersMax": 4,
    "duration": "75 min",
    "durationMinutes": 75,
    "competitive": true,
    "categories": ["Estrategia", "Gestión", "Negociación", "Construcción"],
    "development": "Estrategia, Planificación, Sociabilidad, Negociación, Gestión",
    "summary": "Lanza dados para obtener recursos. Construye caminos y pueblos. Gana el primero con 10 puntos.",
    "videoUrl": "https://www.youtube.com/watch?v=Lh5LcChAzTg",
    "coverImage": "juegos/catan.jpg"
  },
  {
    "title": "Carcassonne",
    "synopsis": "Coloca losetas para construir ciudades y caminos en la Francia medieval.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 7,
    "playersMin": 2,
    "playersMax": 5,
    "duration": "35 min",
    "durationMinutes": 35,
    "competitive": true,
    "categories": ["Estrategia", "Colocación", "Familiar", "Táctico"],
    "development": "Visión espacial, Estrategia, Planificación, Gestión, Paciencia",
    "summary": "Coloca una loseta que encaje y decide si pones un seguidor (meeple) para puntuar áreas.",
    "videoUrl": "https://www.youtube.com/watch?v=eWQP4ysJ8YY",
    "coverImage": "juegos/carcassonne.jpg"
  },
  {
    "title": "Virus!",
    "synopsis": "Completa un cuerpo sano mientras infectas los órganos de tus oponentes.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 6,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Cartas", "Party", "Humor", "Rápido"],
    "development": "Agilidad mental, Estrategia, Toma de decisiones, Atención, Sociabilidad",
    "summary": "Sé el primero en reunir 4 órganos de diferente color totalmente sanos (libres de virus).",
    "videoUrl": "https://www.youtube.com/watch?v=4-Mjo_oTyEk",
    "coverImage": "juegos/virus!.jpg"
  },
  {
    "title": "Dixit",
    "synopsis": "Usa la imaginación para describir cartas con arte surrealista.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 8,
    "playersMin": 3,
    "playersMax": 6,
    "duration": "30 min",
    "durationMinutes": 30,
    "competitive": true,
    "categories": ["Party", "Creatividad", "Familiar"],
    "development": "Imaginación, Empatía, Narración, Deducción, Sociabilidad",
    "summary": "El cuentacuentos dice una pista. El resto elige cartas similares. Hay que adivinar la carta original.",
    "videoUrl": "https://www.youtube.com/watch?v=DVPuPusMFpI",
    "coverImage": "juegos/dixit.jpg"
  },
  {
    "title": "Sagrada",
    "synopsis": "Construye una vidriera de dados siguiendo restricciones de color y número.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 13,
    "playersMin": 1,
    "playersMax": 4,
    "duration": "45 min",
    "durationMinutes": 45,
    "competitive": true,
    "categories": ["Estrategia", "Puzle", "Dados", "Abstracto"],
    "development": "Visión espacial, Lógica, Optimización, Estrategia, Paciencia",
    "summary": "Elige dados y colócalos en tu vidriera respetando las reglas de adyacencia y restricciones de color.",
    "videoUrl": "https://www.youtube.com/watch?v=WZ49d8THdJA",
    "coverImage": "juegos/sagrada.jpg"
  },
  {
    "title": "Sushi Go!",
    "synopsis": "Elige las mejores combinaciones de sushi mientras las cartas rotan en la mesa.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 5,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Cartas", "Draft", "Rápido", "Familiar"],
    "development": "Toma de decisiones, Memoria, Estrategia, Cálculo, Selección",
    "summary": "Quédate una carta y pasa el resto. Consigue puntos haciendo sets de tempura, maki o nigiris.",
    "videoUrl": "https://www.youtube.com/watch?v=WkCfpQFbw78",
    "coverImage": "juegos/sushi_go!.jpg"
  },
  {
    "title": "Exploding Kittens",
    "synopsis": "Una ruleta rusa de cartas con gatos explosivos y mucha mala leche.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 7,
    "playersMin": 2,
    "playersMax": 5,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Cartas", "Humor", "Party"],
    "development": "Gestión de riesgo, Estrategia, Suerte, Atención, Sociabilidad",
    "summary": "Roba cartas hasta que alguien saca un gato explosivo. Usa acciones para evitar explotar.",
    "videoUrl": "https://www.youtube.com/watch?v=FYwUaSrW0ls",
    "coverImage": "juegos/exploding_kittens.jpg"
  },
  {
    "title": "Hero Realms",
    "synopsis": "Combate fantástico donde debes reducir la vida de tu oponente a cero.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 12,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Cartas", "Deck-building", "Fantasía", "Combate"],
    "development": "Estrategia, Planificación, Optimización, Cálculo, Adaptabilidad",
    "summary": "Compra cartas del mercado para mejorar tu mazo y atacar la vida del rival sistemáticamente.",
    "videoUrl": "https://www.youtube.com/watch?v=wLvNx9cXivc",
    "coverImage": "juegos/hero_realms.jpg"
  },
  {
    "title": "Misión Cumplida",
    "synopsis": "Cooperad para completar retos numéricos antes de agotar el mazo.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 8,
    "playersMin": 1,
    "playersMax": 4,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": false,
    "categories": ["Cooperativo", "Cartas", "Lógica"],
    "development": "Trabajo en equipo, Comunicación, Lógica, Planificación, Estrategia",
    "summary": "Cumplid los objetivos de color o número jugando cartas en montones comunes sin hablar directamente.",
    "videoUrl": "https://www.youtube.com/watch?v=GVveiIVRhtE",
    "coverImage": "juegos/mision_cumplida.jpg"
  },
  {
    "title": "Pandemic Respuesta Rápida",
    "synopsis": "Lanza dados a contrarreloj para entregar suministros en ciudades en crisis.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 14,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": false,
    "categories": ["Cooperativo", "Dados", "Tiempo real"],
    "development": "Gestión de crisis, Coordinación, Rapidez, Comunicación, Estrategia",
    "summary": "Tira dados para moverte por el avión, fabricar comida/agua y lanzarlos a las ciudades antes de que el tiempo acabe.",
    "videoUrl": "https://www.youtube.com/watch?v=wikuFK_FOKY",
    "coverImage": "juegos/pandemic_respuesta_rapida.jpg"
  },
  {
    "title": "Jungle Speed",
    "synopsis": "Sé el más rápido en atrapar el tótem cuando las cartas coincidan.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 7,
    "playersMin": 2,
    "playersMax": 10,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Habilidad", "Party", "Reflejos"],
    "development": "Reflejos, Atención, Velocidad, Coordinación, Sociabilidad",
    "summary": "Si el símbolo de tu carta coincide con el de otro, corre a por el tótem central para ganar.",
    "videoUrl": "https://www.youtube.com/watch?v=Kq2WXr5I9os",
    "coverImage": "juegos/jungle_speed.jpg"
  },
  {
    "title": "Fantasma Blitz",
    "synopsis": "Identifica y atrapa rápidamente el objeto correcto según la carta.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 10,
    "playersMin": 2,
    "playersMax": 8,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Reflejos", "Atención", "Party"],
    "development": "Rapidez mental, Percepción, Agilidad, Atención, Sociabilidad",
    "summary": "Si un objeto aparece idéntico en la carta, cógelo. Si no, coge el que no comparta color ni forma.",
    "videoUrl": "https://www.youtube.com/watch?v=cBruixpK1Fg",
    "coverImage": "juegos/fantasma_blitz.jpg"
  },
  {
    "title": "Dobble",
    "synopsis": "Encuentra el símbolo idéntico entre dos cartas antes que los demás.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 6,
    "playersMin": 2,
    "playersMax": 8,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Percepción", "Party", "Familiar"],
    "development": "Atención, Velocidad, Percepción visual, Reflejos, Sociabilidad",
    "summary": "Todas las cartas tienen un símbolo común. Sé el primero en nombrarlo para ganar la carta.",
    "videoUrl": "https://www.youtube.com/watch?v=SNxegbORsls",
    "coverImage": "juegos/dobble.jpg"
  },
  {
    "title": "Match 5",
    "synopsis": "Asocia conceptos y usa tu ingenio para encontrar palabras bajo presión.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 10,
    "playersMin": 2,
    "playersMax": 8,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Party", "Palabras", "Creatividad"],
    "development": "Pensamiento lateral, Agilidad mental, Vocabulario, Creatividad, Sociabilidad",
    "summary": "Tienes tiempo límite para escribir palabras que unan dos categorías aleatorias mostradas por los dados.",
    "videoUrl": "https://www.youtube.com/watch?v=SJL50Zg4U5I",
    "coverImage": "juegos/match_5.jpg"
  },
  {
    "title": "Chromino",
    "synopsis": "Coloca fichas de dominó cromático uniendo al menos dos colores iguales.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 6,
    "playersMin": 2,
    "playersMax": 8,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Lógica", "Colocación", "Abstracto"],
    "development": "Visión espacial, Lógica, Estrategia, Atención, Paciencia",
    "summary": "Coloca tus fichas haciendo que coincidan dos o más cuadrados de color con los ya puestos.",
    "videoUrl": "https://www.youtube.com/watch?v=jdgBCD6rzrM",
    "coverImage": "juegos/chromino.jpg"
  },
  {
    "title": "Cluedo",
    "synopsis": "Resuelve el misterio: quién mató al Dr. Black con qué arma y en qué habitación.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 6,
    "duration": "45 min",
    "durationMinutes": 45,
    "competitive": true,
    "categories": ["Deducción", "Misterio", "Familiar"],
    "development": "Lógica, Deducción, Memoria, Análisis, Sociabilidad",
    "summary": "Muévete por la mansión y haz sugerencias. Descarta sospechosos hasta encontrar la verdad por eliminación.",
    "videoUrl": "https://www.youtube.com/watch?v=iUEuLEDGW9k",
    "coverImage": "juegos/cluedo.jpg"
  },
  {
    "title": "The Game",
    "synopsis": "Intentad colocar todas las cartas en orden ascendente y descendente sin hablar.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 8,
    "playersMin": 1,
    "playersMax": 5,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": false,
    "categories": ["Cooperativo", "Cartas", "Lógica"],
    "development": "Comunicación no verbal, Lógica, Planificación, Estrategia, Trabajo en equipo",
    "summary": "Debéis jugar cartas en 4 montones (2 suben, 2 bajan). No podéis decir los números exactos que tenéis.",
    "videoUrl": "https://www.youtube.com/watch?v=Y91m8SAYbdc",
    "coverImage": "juegos/the_game.jpg"
  },
  {
    "title": "Samurai Sword",
    "synopsis": "Un juego de identidades ocultas y combate en el Japón feudal.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 8,
    "playersMin": 3,
    "playersMax": 7,
    "duration": "45 min",
    "durationMinutes": 45,
    "competitive": true,
    "categories": ["Cartas", "Roles ocultos", "Combate"],
    "development": "Deducción, Estrategia, Roles, Faroleo, Sociabilidad",
    "summary": "Descubre quién es el Shogun, el Samurai o el Ninja mientras atacas con cartas de armas.",
    "videoUrl": "https://www.youtube.com/watch?v=udCXta6aW0E",
    "coverImage": "juegos/samurai_sword.jpg"
  },
  {
    "title": "Spoilers",
    "synopsis": "Engaña a tus amigos con finales falsos de películas de Serie B.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 14,
    "playersMin": 3,
    "playersMax": 6,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Party", "Faroleo", "Cine"],
    "development": "Creatividad, Engaño, Cultura cinematográfica, Interpretación, Sociabilidad",
    "summary": "El 'spoiler' lee una escena. Debes adivinar si el final que propone es real o un invento para engañarte.",
    "videoUrl": "https://www.youtube.com/watch?v=dFgNbmiRaFY",
    "coverImage": "juegos/spoilers.jpg"
  },
  {
    "title": "Pocket Invaders",
    "synopsis": "Cruenta batalla espacial con estética retro que mezcla ajedrez y azar.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Estrategia", "Puzle", "Abstracto"],
    "development": "Estrategia, Táctica, Planificación, Gestión de azar, Geometría",
    "summary": "Mueve tus naves como en el ajedrez. Introduce nuevas naves lanzando dados. Captura la nave nodriza rival.",
    "videoUrl": "https://www.youtube.com/watch?v=Gt-wq1nGO-c",
    "coverImage": "juegos/pocket_invaders.jpg"
  },
  {
    "title": "City Blox",
    "synopsis": "Construye edificios con piezas tipo LEGO encajándolas en moldes.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 6,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Construcción", "Habilidad", "Puzle"],
    "development": "Visión espacial, Psicomotricidad, Lógica, Planificación, Paciencia",
    "summary": "Sé el primero en completar tus tres manzanas (casa, colegio, súper) encajando piezas en los moldes.",
    "videoUrl": "https://www.youtube.com/watch?v=ZgyjbVIp9Cs",
    "coverImage": "juegos/city_blox.jpg"
  },
  {
    "title": "Party & Co Extreme 2.0",
    "synopsis": "Supera pruebas de dibujo, mímica y preguntas para alcanzar los objetivos.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 14,
    "playersMin": 3,
    "playersMax": 20,
    "duration": "45 min",
    "durationMinutes": 45,
    "competitive": true,
    "categories": ["Party", "Habilidad", "Mímica"],
    "development": "Expresividad, Cultura general, Trabajo en equipo, Agilidad, Sociabilidad",
    "summary": "Completa las pruebas indicadas en tus tarjetas de objetivo para ganar cacahuetes y la partida.",
    "videoUrl": "https://www.youtube.com/watch?v=w_i2CyjOz1Q",
    "coverImage": "juegos/party_and_co_extreme_2.0.jpg"
  },
  {
    "title": "Jenga",
    "synopsis": "Extrae bloques de madera de una torre y colócalos arriba sin que caiga.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 6,
    "playersMin": 1,
    "playersMax": 6,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Habilidad", "Destreza", "Familiar"],
    "development": "Psicomotricidad fina, Paciencia, Resolución de problemas, Equilibrio, Concentración",
    "summary": "Saca un bloque con una sola mano y ponlo en la cima. Pierde quien derribe la torre.",
    "videoUrl": "https://www.youtube.com/watch?v=DVsZQ2iPt4U",
    "coverImage": "juegos/jenga.jpg"
  },
  {
    "title": "4 en raya",
    "synopsis": "Consigue alinear cuatro fichas de tu color antes que tu rival.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 6,
    "playersMin": 2,
    "playersMax": 2,
    "duration": "10 min",
    "durationMinutes": 10,
    "competitive": true,
    "categories": ["Estrategia", "Lógica", "Clásico"],
    "development": "Visión espacial, Estrategia, Lógica, Anticipación, Paciencia",
    "summary": "Suelta fichas por turnos. Gana quien conecte 4 en línea vertical, horizontal o diagonal.",
    "videoUrl": "https://www.youtube.com/watch?v=JBSbiilzg9U4",
    "coverImage": "juegos/4_en_raya.jpg"
  },
  {
    "title": "Ajedrez",
    "synopsis": "Duelo de mentes sobre un tablero de 64 casillas con piezas de distintos movimientos.",
    "difficulty": "Alta (4/5)",
    "difficultyLevel": 4,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 2,
    "duration": "60 min",
    "durationMinutes": 60,
    "competitive": true,
    "categories": ["Estrategia", "Lógica", "Clásico"],
    "development": "Estrategia, Concentración, Análisis, Planificación, Paciencia",
    "summary": "Mueve tus piezas para amenazar al rey rival. El juego acaba con el Jaque Mate.",
    "videoUrl": "https://www.youtube.com/watch?v=3VOa8bO1RX4",
    "coverImage": "juegos/ajedrez.jpg"
  },
  {
    "title": "Damas",
    "synopsis": "Captura todas las fichas del oponente saltando sobre ellas en el tablero.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 6,
    "playersMin": 2,
    "playersMax": 2,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Estrategia", "Lógica", "Clásico"],
    "development": "Planificación, Estrategia, Lógica, Anticipación, Paciencia",
    "summary": "Mueve en diagonal. Salta sobre las fichas rivales para eliminarlas. Llega al fondo para coronar dama.",
    "videoUrl": "https://www.youtube.com/watch?v=hz9RLzqGEbo",
    "coverImage": "juegos/damas.jpg"
  },
  {
    "title": "Dominó",
    "synopsis": "Une fichas por sus valores numéricos hasta quedarte sin ninguna.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 6,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Lógica", "Clásico", "Familiar"],
    "development": "Cálculo mental, Estrategia, Memoria, Lógica, Sociabilidad",
    "summary": "Coloca fichas que coincidan con los extremos abiertos. El primero en quedarse sin fichas gana.",
    "videoUrl": "https://www.youtube.com/watch?v=3R0KLW40XTE",
    "coverImage": "juegos/domino.jpg"
  },
  {
    "title": "Baraja Española",
    "synopsis": "Baraja tradicional para juegos como el Tute, Mus o la Escoba.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 6,
    "playersMin": 1,
    "playersMax": 6,
    "duration": "Varia",
    "durationMinutes": 30,
    "competitive": true,
    "categories": ["Cartas", "Tradicional", "Familiar"],
    "development": "Memoria, Estrategia, Cálculo, Picaresca, Sociabilidad",
    "summary": "Varía según el juego elegido (Escoba: sumar 15, Chinchón: combinar cartas, etc.).",
    "videoUrl": "https://www.youtube.com/watch?v=Y36idR-qJyw&list=PLEIdrY0iUqfSselaSPXE87q8z6UhEb2sM",
    "coverImage": "juegos/baraja_espanola.jpg"
  },
  {
    "title": "Rummikub",
    "synopsis": "Forma series o grupos de números sobre la mesa con tus fichas.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "30 min",
    "durationMinutes": 30,
    "competitive": true,
    "categories": ["Lógica", "Números", "Familiar"],
    "development": "Cálculo, Agilidad mental, Visión espacial, Estrategia, Paciencia",
    "summary": "Combina tus fichas en escaleras o tríos. Puedes manipular lo que ya hay en mesa para encajar tus piezas.",
    "videoUrl": "https://www.youtube.com/watch?v=JTT_aiOqCWk",
    "coverImage": "juegos/rummikub.jpg"
  },
  {
    "title": "5 Alive",
    "synopsis": "Juego de cartas rápido donde debes evitar que el valor total pase de 21.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 7,
    "playersMin": 2,
    "playersMax": 6,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Cartas", "Rápido", "Familiar"],
    "development": "Cálculo mental, Agilidad, Toma de decisiones, Atención, Sociabilidad",
    "summary": "Juega cartas sumando su valor al total. Si pasas de 21, pierdes una vida. Sé el último con vidas.",
    "videoUrl": "https://www.youtube.com/watch?v=sNWkEn6RsOg",
    "coverImage": "juegos/5_alive.jpg"
  },
  {
    "title": "Walkie Talkie",
    "synopsis": "Juego cooperativo frenético de asociación de palabras y colores contra el reloj.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 8,
    "duration": "5 min",
    "durationMinutes": 5,
    "competitive": false,
    "categories": ["Cooperativo", "Palabras", "Party"],
    "development": "Agilidad mental, Asociación, Comunicación, Rapidez, Sociabilidad",
    "summary": "Di una palabra que empiece por tu letra y coincida con el color de la mesa para descartar.",
    "videoUrl": "https://www.youtube.com/watch?v=G9BjalSRMdc",
    "coverImage": "juegos/walkie_talkie.jpg"
  },
  {
    "title": "Pajarracos",
    "synopsis": "Protege tus frutas de los pájaros de los rivales mientras les envías los tuyos.",
    "difficulty": "Baja (2/5)",
    "difficultyLevel": 2,
    "minAge": 8,
    "playersMin": 2,
    "playersMax": 5,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Cartas", "Familiar", "Interacción"],
    "development": "Estrategia, Atención, Toma de decisiones, Planificación, Sociabilidad",
    "summary": "Siembra cartas de fruta y usa cartas de pájaros para robar puntos a los demás jugadores.",
    "videoUrl": "https://www.youtube.com/watch?v=fRoqAVMM-uY",
    "coverImage": "juegos/pajarracos.jpg"
  },
  {
    "title": "Red 7",
    "synopsis": "Un juego donde la regla para ganar cambia en cada turno según las cartas jugadas.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 9,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "10 min",
    "durationMinutes": 10,
    "competitive": true,
    "categories": ["Cartas", "Lógica", "Rápido"],
    "development": "Lógica, Adaptabilidad, Anticipación, Toma de decisiones, Estrategia",
    "summary": "Al final de tu turno tienes que ir ganando con la regla actual o cambiarla para no perder.",
    "videoUrl": "https://www.youtube.com/watch?v=P60r-iMGNWI",
    "coverImage": "juegos/red_7.jpg"
  },
  {
    "title": "Saboteur",
    "synopsis": "Enanos mineros buscan oro mientras un saboteador intenta impedir que lleguen.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 8,
    "playersMin": 3,
    "playersMax": 10,
    "duration": "30 min",
    "durationMinutes": 30,
    "competitive": true,
    "categories": ["Roles ocultos", "Faroleo", "Estrategia"],
    "development": "Deducción, Engaño, Sociabilidad, Estrategia, Trabajo en equipo",
    "summary": "Construye un camino con cartas hasta el oro. Si eres el saboteador, bloquéalo sin que te pillen.",
    "videoUrl": "https://www.youtube.com/watch?v=_287Gf9Kd2I",
    "coverImage": "juegos/saboteur.jpg"
  },
  {
    "title": "Holi: Festival de Colores",
    "synopsis": "Tablero 3D donde lanzas polvos de colores para controlar el espacio.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 10,
    "playersMin": 2,
    "playersMax": 4,
    "duration": "40 min",
    "durationMinutes": 40,
    "competitive": true,
    "categories": ["Estrategia", "Abstracto", "3D"],
    "development": "Visión espacial, Planificación, Estrategia, Optimización, Sociabilidad",
    "summary": "Mueve tu ficha por los niveles y expande tus cartas de patrón de color para puntuar más.",
    "videoUrl": "https://www.youtube.com/watch?v=_wjtYF7Y4Qo",
    "coverImage": "juegos/holi_festival_de_colores.jpg"
  },
  {
    "title": "Uno",
    "synopsis": "El famoso juego de cartas de colores donde debes ser el primero en quedarte sin nada.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 7,
    "playersMin": 2,
    "playersMax": 10,
    "duration": "20 min",
    "durationMinutes": 20,
    "competitive": true,
    "categories": ["Cartas", "Familiar", "Clásico"],
    "development": "Velocidad, Atención, Estrategia básica, Reflejos, Sociabilidad",
    "summary": "Empareja cartas por color o número. Di 'Uno' cuando te quede una o te penalizarán.",
    "videoUrl": "https://www.youtube.com/watch?v=bXOU4SuXdlg",
    "coverImage": "juegos/uno.jpg"
  },
  {
    "title": "Jenga circular",
    "synopsis": "Torre de madera cilíndrica que desafía la gravedad y tu pulso.",
    "difficulty": "Muy Baja (1/5)",
    "difficultyLevel": 1,
    "minAge": 6,
    "playersMin": 1,
    "playersMax": 6,
    "duration": "15 min",
    "durationMinutes": 15,
    "competitive": true,
    "categories": ["Habilidad", "Destreza", "Familiar"],
    "development": "Psicomotricidad fina, Paciencia, Concentración, Equilibrio, Precisión",
    "summary": "Saca una pieza de la torre y ponla arriba con cuidado. Pierde quien derribe la estructura.",
    "videoUrl": "https://www.youtube.com/watch?v=DVsZQ2iPt4U",
    "coverImage": "juegos/jenga_circular.jpg"
  },
  {
    "title": "Juego de Póquer",
    "synopsis": "Maletín de apuestas basado en la psicología y la mejor mano de cartas.",
    "difficulty": "Media (3/5)",
    "difficultyLevel": 3,
    "minAge": 18,
    "playersMin": 2,
    "playersMax": 10,
    "duration": "120 min",
    "durationMinutes": 120,
    "competitive": true,
    "categories": ["Cartas", "Apuestas", "Estrategia"],
    "development": "Psicología, Cálculo, Engaño, Autocontrol, Estrategia",
    "summary": "Realiza apuestas según tus cartas. El ganador se lleva el bote por mejor mano o por faroleo.",
    "videoUrl": "https://www.youtube.com/watch?v=nx6f5kS84HY",
    "coverImage": "juegos/juego_de_poker.jpg"
  }
];